//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NpmScopeRegistry) DeepCopyInto(out *NpmScopeRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NpmScopeRegistry.
func (in *NpmScopeRegistry) DeepCopy() *NpmScopeRegistry {
	if in == nil {
		return nil
	}
	out := new(NpmScopeRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaveCascade) DeepCopyInto(out *WaveCascade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaveCascade.
func (in *WaveCascade) DeepCopy() *WaveCascade {
	if in == nil {
		return nil
	}
	out := new(WaveCascade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WaveCascade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaveCascadeList) DeepCopyInto(out *WaveCascadeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WaveCascade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaveCascadeList.
func (in *WaveCascadeList) DeepCopy() *WaveCascadeList {
	if in == nil {
		return nil
	}
	out := new(WaveCascadeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WaveCascadeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaveCascadeSpec) DeepCopyInto(out *WaveCascadeSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	out.Policy = in.Policy
	if in.NpmScopeRegistries != nil {
		in, out := &in.NpmScopeRegistries, &out.NpmScopeRegistries
		*out = make([]NpmScopeRegistry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaveCascadeSpec.
func (in *WaveCascadeSpec) DeepCopy() *WaveCascadeSpec {
	if in == nil {
		return nil
	}
	out := new(WaveCascadeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaveCascadeStatus) DeepCopyInto(out *WaveCascadeStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaveCascadeStatus.
func (in *WaveCascadeStatus) DeepCopy() *WaveCascadeStatus {
	if in == nil {
		return nil
	}
	out := new(WaveCascadeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WavePolicy) DeepCopyInto(out *WavePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WavePolicy.
func (in *WavePolicy) DeepCopy() *WavePolicy {
	if in == nil {
		return nil
	}
	out := new(WavePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaveScope) DeepCopyInto(out *WaveScope) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InternalPrefixes != nil {
		in, out := &in.InternalPrefixes, &out.InternalPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaveScope.
func (in *WaveScope) DeepCopy() *WaveScope {
	if in == nil {
		return nil
	}
	out := new(WaveScope)
	in.DeepCopyInto(out)
	return out
}
